# Generated by Django 4.1.1 on 2022-09-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='Taluka',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='taluka',
        ),
        migrations.RenameField(
            model_name='taluka',
            old_name='country',
            new_name='district',
        ),
    ]
