# Generated by Django 4.1.1 on 2022-09-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_country_district_rename_city_taluka_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taluka',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='District',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='district',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='taluka',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='district',
            new_name='country',
        ),
    ]
